//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace AgilityCIS.Orion.Shell.AgilitySvcProxy {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxIndicator", Namespace="http://schemas.datacontract.org/2004/07/AgilityCIS.Orion.Services.DataContracts")]
    public partial class TaxIndicator : object, System.ComponentModel.INotifyPropertyChanged {
		#region Fields (3) 

        private string TaxIndicatorCodeField;
        private string TaxIndicatorDescField;
        private int TaxIndicatorIdField;

		#endregion Fields 

		#region Properties (3) 

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxIndicatorCode {
            get {
                return this.TaxIndicatorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxIndicatorCodeField, value) != true)) {
                    this.TaxIndicatorCodeField = value;
                    this.RaisePropertyChanged("TaxIndicatorCode");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxIndicatorDesc {
            get {
                return this.TaxIndicatorDescField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxIndicatorDescField, value) != true)) {
                    this.TaxIndicatorDescField = value;
                    this.RaisePropertyChanged("TaxIndicatorDesc");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaxIndicatorId {
            get {
                return this.TaxIndicatorIdField;
            }
            set {
                if ((this.TaxIndicatorIdField.Equals(value) != true)) {
                    this.TaxIndicatorIdField = value;
                    this.RaisePropertyChanged("TaxIndicatorId");
                }
            }
        }

		#endregion Properties 

		#region Delegates and Events (1) 

		// Events (1) 

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		#endregion Delegates and Events 

		#region Methods (1) 

		// Protected Methods (1) 

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

		#endregion Methods 
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.agility.com/contracts", ConfigurationName="AgilitySvcProxy.IAgilityService")]
    public interface IAgilityService {
		#region Operations (32) 

        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="DeleteCustomer", ReplyAction="http://schemas.agility.com/contracts/IAgilityService/DeleteCustomerResponse")]
        System.IAsyncResult BeginDeleteCustomer(int seqPartyId, System.AsyncCallback callback, object asyncState);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetBillingCycles", ReplyAction="http://schemas.agility.com/contracts/IAgilityService/GetBillingCyclesResponse")]
        System.IAsyncResult BeginGetBillingCycles(System.AsyncCallback callback, object asyncState);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetCardTypes", ReplyAction="http://schemas.agility.com/contracts/IAgilityService/GetCardTypesResponse")]
        System.IAsyncResult BeginGetCardTypes(System.AsyncCallback callback, object asyncState);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetCreditCheckScores", ReplyAction="http://schemas.agility.com/contracts/IAgilityService/GetCreditCheckScoresResponse" +
            "")]
        System.IAsyncResult BeginGetCreditCheckScores(System.AsyncCallback callback, object asyncState);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetCreditControlStatus", ReplyAction="http://schemas.agility.com/contracts/IAgilityService/GetCreditControlStatusRespon" +
            "se")]
        System.IAsyncResult BeginGetCreditControlStatus(System.AsyncCallback callback, object asyncState);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetCustomerDetails", ReplyAction="http://schemas.agility.com/contracts/IAgilityService/GetCustomerDetailsResponse")]
        System.IAsyncResult BeginGetCustomerDetails(int customerNo, System.AsyncCallback callback, object asyncState);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetCustomers", ReplyAction="http://schemas.agility.com/contracts/IAgilityService/GetCustomersResponse")]
        System.IAsyncResult BeginGetCustomers(System.AsyncCallback callback, object asyncState);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetCustomerSummaryDetails", ReplyAction="http://schemas.agility.com/contracts/IAgilityService/GetCustomerSummaryDetailsRes" +
            "ponse")]
        System.IAsyncResult BeginGetCustomerSummaryDetails(int seqPartyId, System.AsyncCallback callback, object asyncState);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetInvoiceDeliveries", ReplyAction="http://schemas.agility.com/contracts/IAgilityService/GetInvoiceDeliveriesResponse" +
            "")]
        System.IAsyncResult BeginGetInvoiceDeliveries(System.AsyncCallback callback, object asyncState);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetInvoiceStyles", ReplyAction="http://schemas.agility.com/contracts/IAgilityService/GetInvoiceStylesResponse")]
        System.IAsyncResult BeginGetInvoiceStyles(System.AsyncCallback callback, object asyncState);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetPaymentMethods", ReplyAction="http://schemas.agility.com/contracts/IAgilityService/GetPaymentMethodsResponse")]
        System.IAsyncResult BeginGetPaymentMethods(System.AsyncCallback callback, object asyncState);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetTaxIndicators", ReplyAction="http://schemas.agility.com/contracts/IAgilityService/GetTaxIndicatorsResponse")]
        System.IAsyncResult BeginGetTaxIndicators(System.AsyncCallback callback, object asyncState);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetTreatmentTypes", ReplyAction="http://schemas.agility.com/contracts/IAgilityService/GetTreatmentTypesResponse")]
        System.IAsyncResult BeginGetTreatmentTypes(System.AsyncCallback callback, object asyncState);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="Login", ReplyAction="http://schemas.agility.com/contracts/IAgilityService/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgilityCIS.Orion.Services.AgilitySvcProxy.FaultDetail), Action="http://schemas.agility.com/contracts/IAgilityService/LoginFaultDetailFault", Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/AgilityCIS.Orion.Services.DataContracts")]
        System.IAsyncResult BeginLogin(AgilityCIS.Orion.Services.AgilitySvcProxy.User user, System.AsyncCallback callback, object asyncState);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="SaveCustomerDetails", ReplyAction="http://schemas.agility.com/contracts/IAgilityService/SaveCustomerDetailsResponse")]
        System.IAsyncResult BeginSaveCustomerDetails(AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerDetails customerDetails, System.AsyncCallback callback, object asyncState);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="SearchCustomers", ReplyAction="http://schemas.agility.com/contracts/IAgilityService/SearchCustomersResponse")]
        System.IAsyncResult BeginSearchCustomers(AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerSearchCriteria criteria, System.AsyncCallback callback, object asyncState);

        bool EndDeleteCustomer(System.IAsyncResult result);

        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.BillingCycle> EndGetBillingCycles(System.IAsyncResult result);

        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CardType> EndGetCardTypes(System.IAsyncResult result);

        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CreditCheckScore> EndGetCreditCheckScores(System.IAsyncResult result);

        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CreditControlStatus> EndGetCreditControlStatus(System.IAsyncResult result);

        AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerDetails EndGetCustomerDetails(System.IAsyncResult result);

        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.Customer> EndGetCustomers(System.IAsyncResult result);

        AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerSummary EndGetCustomerSummaryDetails(System.IAsyncResult result);

        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.InvoiceDelivery> EndGetInvoiceDeliveries(System.IAsyncResult result);

        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.InvoiceStyle> EndGetInvoiceStyles(System.IAsyncResult result);

        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.PayMethod> EndGetPaymentMethods(System.IAsyncResult result);

        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Shell.AgilitySvcProxy.TaxIndicator> EndGetTaxIndicators(System.IAsyncResult result);

        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.TreatmentType> EndGetTreatmentTypes(System.IAsyncResult result);

        AgilityCIS.Orion.Services.AgilitySvcProxy.User EndLogin(System.IAsyncResult result);

        bool EndSaveCustomerDetails(System.IAsyncResult result);

        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.Customer> EndSearchCustomers(System.IAsyncResult result);

		#endregion Operations 
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAgilityServiceChannel : AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService, System.ServiceModel.IClientChannel {

}
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBillingCyclesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
		#region Fields (1) 

        private object[] results;

		#endregion Fields 

		#region Constructors (1) 

        public GetBillingCyclesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

		#endregion Constructors 

		#region Properties (1) 

        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.BillingCycle> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.BillingCycle>)(this.results[0]));
            }
        }

		#endregion Properties 
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCustomerDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
		#region Fields (1) 

        private object[] results;

		#endregion Fields 

		#region Constructors (1) 

        public GetCustomerDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

		#endregion Constructors 

		#region Properties (1) 

        public AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerDetails Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerDetails)(this.results[0]));
            }
        }

		#endregion Properties 
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
		#region Fields (1) 

        private object[] results;

		#endregion Fields 

		#region Constructors (1) 

        public GetCustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

		#endregion Constructors 

		#region Properties (1) 

        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.Customer> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.Customer>)(this.results[0]));
            }
        }

		#endregion Properties 
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCustomerSummaryDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
		#region Fields (1) 

        private object[] results;

		#endregion Fields 

		#region Constructors (1) 

        public GetCustomerSummaryDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

		#endregion Constructors 

		#region Properties (1) 

        public AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerSummary Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerSummary)(this.results[0]));
            }
        }

		#endregion Properties 
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
		#region Fields (1) 

        private object[] results;

		#endregion Fields 

		#region Constructors (1) 

        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

		#endregion Constructors 

		#region Properties (1) 

        public AgilityCIS.Orion.Services.AgilitySvcProxy.User Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AgilityCIS.Orion.Services.AgilitySvcProxy.User)(this.results[0]));
            }
        }

		#endregion Properties 
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveCustomerDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
		#region Fields (1) 

        private object[] results;

		#endregion Fields 

		#region Constructors (1) 

        public SaveCustomerDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

		#endregion Constructors 

		#region Properties (1) 

        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }

		#endregion Properties 
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchCustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
		#region Fields (1) 

        private object[] results;

		#endregion Fields 

		#region Constructors (1) 

        public SearchCustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

		#endregion Constructors 

		#region Properties (1) 

        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.Customer> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.Customer>)(this.results[0]));
            }
        }

		#endregion Properties 
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetInvoiceStylesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
		#region Fields (1) 

        private object[] results;

		#endregion Fields 

		#region Constructors (1) 

        public GetInvoiceStylesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

		#endregion Constructors 

		#region Properties (1) 

        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.InvoiceStyle> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.InvoiceStyle>)(this.results[0]));
            }
        }

		#endregion Properties 
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetInvoiceDeliveriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
		#region Fields (1) 

        private object[] results;

		#endregion Fields 

		#region Constructors (1) 

        public GetInvoiceDeliveriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

		#endregion Constructors 

		#region Properties (1) 

        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.InvoiceDelivery> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.InvoiceDelivery>)(this.results[0]));
            }
        }

		#endregion Properties 
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCreditCheckScoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
		#region Fields (1) 

        private object[] results;

		#endregion Fields 

		#region Constructors (1) 

        public GetCreditCheckScoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

		#endregion Constructors 

		#region Properties (1) 

        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CreditCheckScore> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CreditCheckScore>)(this.results[0]));
            }
        }

		#endregion Properties 
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPaymentMethodsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
		#region Fields (1) 

        private object[] results;

		#endregion Fields 

		#region Constructors (1) 

        public GetPaymentMethodsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

		#endregion Constructors 

		#region Properties (1) 

        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.PayMethod> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.PayMethod>)(this.results[0]));
            }
        }

		#endregion Properties 
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCardTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
		#region Fields (1) 

        private object[] results;

		#endregion Fields 

		#region Constructors (1) 

        public GetCardTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

		#endregion Constructors 

		#region Properties (1) 

        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CardType> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CardType>)(this.results[0]));
            }
        }

		#endregion Properties 
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCreditControlStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
		#region Fields (1) 

        private object[] results;

		#endregion Fields 

		#region Constructors (1) 

        public GetCreditControlStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

		#endregion Constructors 

		#region Properties (1) 

        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CreditControlStatus> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CreditControlStatus>)(this.results[0]));
            }
        }

		#endregion Properties 
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTreatmentTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
		#region Fields (1) 

        private object[] results;

		#endregion Fields 

		#region Constructors (1) 

        public GetTreatmentTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

		#endregion Constructors 

		#region Properties (1) 

        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.TreatmentType> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.TreatmentType>)(this.results[0]));
            }
        }

		#endregion Properties 
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
		#region Fields (1) 

        private object[] results;

		#endregion Fields 

		#region Constructors (1) 

        public DeleteCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

		#endregion Constructors 

		#region Properties (1) 

        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }

		#endregion Properties 
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTaxIndicatorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
		#region Fields (1) 

        private object[] results;

		#endregion Fields 

		#region Constructors (1) 

        public GetTaxIndicatorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

		#endregion Constructors 

		#region Properties (1) 

        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Shell.AgilitySvcProxy.TaxIndicator> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Shell.AgilitySvcProxy.TaxIndicator>)(this.results[0]));
            }
        }

		#endregion Properties 
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgilityServiceClient : System.ServiceModel.ClientBase<AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService>, AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService {
		#region Fields (54) 

        private BeginOperationDelegate onBeginCloseDelegate;
        private BeginOperationDelegate onBeginDeleteCustomerDelegate;
        private BeginOperationDelegate onBeginGetBillingCyclesDelegate;
        private BeginOperationDelegate onBeginGetCardTypesDelegate;
        private BeginOperationDelegate onBeginGetCreditCheckScoresDelegate;
        private BeginOperationDelegate onBeginGetCreditControlStatusDelegate;
        private BeginOperationDelegate onBeginGetCustomerDetailsDelegate;
        private BeginOperationDelegate onBeginGetCustomersDelegate;
        private BeginOperationDelegate onBeginGetCustomerSummaryDetailsDelegate;
        private BeginOperationDelegate onBeginGetInvoiceDeliveriesDelegate;
        private BeginOperationDelegate onBeginGetInvoiceStylesDelegate;
        private BeginOperationDelegate onBeginGetPaymentMethodsDelegate;
        private BeginOperationDelegate onBeginGetTaxIndicatorsDelegate;
        private BeginOperationDelegate onBeginGetTreatmentTypesDelegate;
        private BeginOperationDelegate onBeginLoginDelegate;
        private BeginOperationDelegate onBeginOpenDelegate;
        private BeginOperationDelegate onBeginSaveCustomerDetailsDelegate;
        private BeginOperationDelegate onBeginSearchCustomersDelegate;
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        private System.Threading.SendOrPostCallback onDeleteCustomerCompletedDelegate;
        private EndOperationDelegate onEndCloseDelegate;
        private EndOperationDelegate onEndDeleteCustomerDelegate;
        private EndOperationDelegate onEndGetBillingCyclesDelegate;
        private EndOperationDelegate onEndGetCardTypesDelegate;
        private EndOperationDelegate onEndGetCreditCheckScoresDelegate;
        private EndOperationDelegate onEndGetCreditControlStatusDelegate;
        private EndOperationDelegate onEndGetCustomerDetailsDelegate;
        private EndOperationDelegate onEndGetCustomersDelegate;
        private EndOperationDelegate onEndGetCustomerSummaryDetailsDelegate;
        private EndOperationDelegate onEndGetInvoiceDeliveriesDelegate;
        private EndOperationDelegate onEndGetInvoiceStylesDelegate;
        private EndOperationDelegate onEndGetPaymentMethodsDelegate;
        private EndOperationDelegate onEndGetTaxIndicatorsDelegate;
        private EndOperationDelegate onEndGetTreatmentTypesDelegate;
        private EndOperationDelegate onEndLoginDelegate;
        private EndOperationDelegate onEndOpenDelegate;
        private EndOperationDelegate onEndSaveCustomerDetailsDelegate;
        private EndOperationDelegate onEndSearchCustomersDelegate;
        private System.Threading.SendOrPostCallback onGetBillingCyclesCompletedDelegate;
        private System.Threading.SendOrPostCallback onGetCardTypesCompletedDelegate;
        private System.Threading.SendOrPostCallback onGetCreditCheckScoresCompletedDelegate;
        private System.Threading.SendOrPostCallback onGetCreditControlStatusCompletedDelegate;
        private System.Threading.SendOrPostCallback onGetCustomerDetailsCompletedDelegate;
        private System.Threading.SendOrPostCallback onGetCustomersCompletedDelegate;
        private System.Threading.SendOrPostCallback onGetCustomerSummaryDetailsCompletedDelegate;
        private System.Threading.SendOrPostCallback onGetInvoiceDeliveriesCompletedDelegate;
        private System.Threading.SendOrPostCallback onGetInvoiceStylesCompletedDelegate;
        private System.Threading.SendOrPostCallback onGetPaymentMethodsCompletedDelegate;
        private System.Threading.SendOrPostCallback onGetTaxIndicatorsCompletedDelegate;
        private System.Threading.SendOrPostCallback onGetTreatmentTypesCompletedDelegate;
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        private System.Threading.SendOrPostCallback onSaveCustomerDetailsCompletedDelegate;
        private System.Threading.SendOrPostCallback onSearchCustomersCompletedDelegate;

		#endregion Fields 

		#region Constructors (5) 

        public AgilityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }

        public AgilityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }

        public AgilityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }

        public AgilityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }

        public AgilityServiceClient() {
        }

		#endregion Constructors 

		#region Properties (1) 

        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }

		#endregion Properties 

		#region Delegates and Events (18) 

		// Events (18) 

        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;

        public event System.EventHandler<DeleteCustomerCompletedEventArgs> DeleteCustomerCompleted;

        public event System.EventHandler<GetBillingCyclesCompletedEventArgs> GetBillingCyclesCompleted;

        public event System.EventHandler<GetCardTypesCompletedEventArgs> GetCardTypesCompleted;

        public event System.EventHandler<GetCreditCheckScoresCompletedEventArgs> GetCreditCheckScoresCompleted;

        public event System.EventHandler<GetCreditControlStatusCompletedEventArgs> GetCreditControlStatusCompleted;

        public event System.EventHandler<GetCustomerDetailsCompletedEventArgs> GetCustomerDetailsCompleted;

        public event System.EventHandler<GetCustomersCompletedEventArgs> GetCustomersCompleted;

        public event System.EventHandler<GetCustomerSummaryDetailsCompletedEventArgs> GetCustomerSummaryDetailsCompleted;

        public event System.EventHandler<GetInvoiceDeliveriesCompletedEventArgs> GetInvoiceDeliveriesCompleted;

        public event System.EventHandler<GetInvoiceStylesCompletedEventArgs> GetInvoiceStylesCompleted;

        public event System.EventHandler<GetPaymentMethodsCompletedEventArgs> GetPaymentMethodsCompleted;

        public event System.EventHandler<GetTaxIndicatorsCompletedEventArgs> GetTaxIndicatorsCompleted;

        public event System.EventHandler<GetTreatmentTypesCompletedEventArgs> GetTreatmentTypesCompleted;

        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;

        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;

        public event System.EventHandler<SaveCustomerDetailsCompletedEventArgs> SaveCustomerDetailsCompleted;

        public event System.EventHandler<SearchCustomersCompletedEventArgs> SearchCustomersCompleted;

		#endregion Delegates and Events 

		#region Methods (123) 

		// Public Methods (36) 

        public void CloseAsync() {
            this.CloseAsync(null);
        }

        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }

        public void DeleteCustomerAsync(int seqPartyId) {
            this.DeleteCustomerAsync(seqPartyId, null);
        }

        public void DeleteCustomerAsync(int seqPartyId, object userState) {
            if ((this.onBeginDeleteCustomerDelegate == null)) {
                this.onBeginDeleteCustomerDelegate = new BeginOperationDelegate(this.OnBeginDeleteCustomer);
            }
            if ((this.onEndDeleteCustomerDelegate == null)) {
                this.onEndDeleteCustomerDelegate = new EndOperationDelegate(this.OnEndDeleteCustomer);
            }
            if ((this.onDeleteCustomerCompletedDelegate == null)) {
                this.onDeleteCustomerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteCustomerCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteCustomerDelegate, new object[] {
                        seqPartyId}, this.onEndDeleteCustomerDelegate, this.onDeleteCustomerCompletedDelegate, userState);
        }

        public void GetBillingCyclesAsync() {
            this.GetBillingCyclesAsync(null);
        }

        public void GetBillingCyclesAsync(object userState) {
            if ((this.onBeginGetBillingCyclesDelegate == null)) {
                this.onBeginGetBillingCyclesDelegate = new BeginOperationDelegate(this.OnBeginGetBillingCycles);
            }
            if ((this.onEndGetBillingCyclesDelegate == null)) {
                this.onEndGetBillingCyclesDelegate = new EndOperationDelegate(this.OnEndGetBillingCycles);
            }
            if ((this.onGetBillingCyclesCompletedDelegate == null)) {
                this.onGetBillingCyclesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBillingCyclesCompleted);
            }
            base.InvokeAsync(this.onBeginGetBillingCyclesDelegate, null, this.onEndGetBillingCyclesDelegate, this.onGetBillingCyclesCompletedDelegate, userState);
        }

        public void GetCardTypesAsync() {
            this.GetCardTypesAsync(null);
        }

        public void GetCardTypesAsync(object userState) {
            if ((this.onBeginGetCardTypesDelegate == null)) {
                this.onBeginGetCardTypesDelegate = new BeginOperationDelegate(this.OnBeginGetCardTypes);
            }
            if ((this.onEndGetCardTypesDelegate == null)) {
                this.onEndGetCardTypesDelegate = new EndOperationDelegate(this.OnEndGetCardTypes);
            }
            if ((this.onGetCardTypesCompletedDelegate == null)) {
                this.onGetCardTypesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCardTypesCompleted);
            }
            base.InvokeAsync(this.onBeginGetCardTypesDelegate, null, this.onEndGetCardTypesDelegate, this.onGetCardTypesCompletedDelegate, userState);
        }

        public void GetCreditCheckScoresAsync() {
            this.GetCreditCheckScoresAsync(null);
        }

        public void GetCreditCheckScoresAsync(object userState) {
            if ((this.onBeginGetCreditCheckScoresDelegate == null)) {
                this.onBeginGetCreditCheckScoresDelegate = new BeginOperationDelegate(this.OnBeginGetCreditCheckScores);
            }
            if ((this.onEndGetCreditCheckScoresDelegate == null)) {
                this.onEndGetCreditCheckScoresDelegate = new EndOperationDelegate(this.OnEndGetCreditCheckScores);
            }
            if ((this.onGetCreditCheckScoresCompletedDelegate == null)) {
                this.onGetCreditCheckScoresCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCreditCheckScoresCompleted);
            }
            base.InvokeAsync(this.onBeginGetCreditCheckScoresDelegate, null, this.onEndGetCreditCheckScoresDelegate, this.onGetCreditCheckScoresCompletedDelegate, userState);
        }

        public void GetCreditControlStatusAsync() {
            this.GetCreditControlStatusAsync(null);
        }

        public void GetCreditControlStatusAsync(object userState) {
            if ((this.onBeginGetCreditControlStatusDelegate == null)) {
                this.onBeginGetCreditControlStatusDelegate = new BeginOperationDelegate(this.OnBeginGetCreditControlStatus);
            }
            if ((this.onEndGetCreditControlStatusDelegate == null)) {
                this.onEndGetCreditControlStatusDelegate = new EndOperationDelegate(this.OnEndGetCreditControlStatus);
            }
            if ((this.onGetCreditControlStatusCompletedDelegate == null)) {
                this.onGetCreditControlStatusCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCreditControlStatusCompleted);
            }
            base.InvokeAsync(this.onBeginGetCreditControlStatusDelegate, null, this.onEndGetCreditControlStatusDelegate, this.onGetCreditControlStatusCompletedDelegate, userState);
        }

        public void GetCustomerDetailsAsync(int customerNo) {
            this.GetCustomerDetailsAsync(customerNo, null);
        }

        public void GetCustomerDetailsAsync(int customerNo, object userState) {
            if ((this.onBeginGetCustomerDetailsDelegate == null)) {
                this.onBeginGetCustomerDetailsDelegate = new BeginOperationDelegate(this.OnBeginGetCustomerDetails);
            }
            if ((this.onEndGetCustomerDetailsDelegate == null)) {
                this.onEndGetCustomerDetailsDelegate = new EndOperationDelegate(this.OnEndGetCustomerDetails);
            }
            if ((this.onGetCustomerDetailsCompletedDelegate == null)) {
                this.onGetCustomerDetailsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCustomerDetailsCompleted);
            }
            base.InvokeAsync(this.onBeginGetCustomerDetailsDelegate, new object[] {
                        customerNo}, this.onEndGetCustomerDetailsDelegate, this.onGetCustomerDetailsCompletedDelegate, userState);
        }

        public void GetCustomersAsync() {
            this.GetCustomersAsync(null);
        }

        public void GetCustomersAsync(object userState) {
            if ((this.onBeginGetCustomersDelegate == null)) {
                this.onBeginGetCustomersDelegate = new BeginOperationDelegate(this.OnBeginGetCustomers);
            }
            if ((this.onEndGetCustomersDelegate == null)) {
                this.onEndGetCustomersDelegate = new EndOperationDelegate(this.OnEndGetCustomers);
            }
            if ((this.onGetCustomersCompletedDelegate == null)) {
                this.onGetCustomersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCustomersCompleted);
            }
            base.InvokeAsync(this.onBeginGetCustomersDelegate, null, this.onEndGetCustomersDelegate, this.onGetCustomersCompletedDelegate, userState);
        }

        public void GetCustomerSummaryDetailsAsync(int seqPartyId) {
            this.GetCustomerSummaryDetailsAsync(seqPartyId, null);
        }

        public void GetCustomerSummaryDetailsAsync(int seqPartyId, object userState) {
            if ((this.onBeginGetCustomerSummaryDetailsDelegate == null)) {
                this.onBeginGetCustomerSummaryDetailsDelegate = new BeginOperationDelegate(this.OnBeginGetCustomerSummaryDetails);
            }
            if ((this.onEndGetCustomerSummaryDetailsDelegate == null)) {
                this.onEndGetCustomerSummaryDetailsDelegate = new EndOperationDelegate(this.OnEndGetCustomerSummaryDetails);
            }
            if ((this.onGetCustomerSummaryDetailsCompletedDelegate == null)) {
                this.onGetCustomerSummaryDetailsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCustomerSummaryDetailsCompleted);
            }
            base.InvokeAsync(this.onBeginGetCustomerSummaryDetailsDelegate, new object[] {
                        seqPartyId}, this.onEndGetCustomerSummaryDetailsDelegate, this.onGetCustomerSummaryDetailsCompletedDelegate, userState);
        }

        public void GetInvoiceDeliveriesAsync() {
            this.GetInvoiceDeliveriesAsync(null);
        }

        public void GetInvoiceDeliveriesAsync(object userState) {
            if ((this.onBeginGetInvoiceDeliveriesDelegate == null)) {
                this.onBeginGetInvoiceDeliveriesDelegate = new BeginOperationDelegate(this.OnBeginGetInvoiceDeliveries);
            }
            if ((this.onEndGetInvoiceDeliveriesDelegate == null)) {
                this.onEndGetInvoiceDeliveriesDelegate = new EndOperationDelegate(this.OnEndGetInvoiceDeliveries);
            }
            if ((this.onGetInvoiceDeliveriesCompletedDelegate == null)) {
                this.onGetInvoiceDeliveriesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetInvoiceDeliveriesCompleted);
            }
            base.InvokeAsync(this.onBeginGetInvoiceDeliveriesDelegate, null, this.onEndGetInvoiceDeliveriesDelegate, this.onGetInvoiceDeliveriesCompletedDelegate, userState);
        }

        public void GetInvoiceStylesAsync() {
            this.GetInvoiceStylesAsync(null);
        }

        public void GetInvoiceStylesAsync(object userState) {
            if ((this.onBeginGetInvoiceStylesDelegate == null)) {
                this.onBeginGetInvoiceStylesDelegate = new BeginOperationDelegate(this.OnBeginGetInvoiceStyles);
            }
            if ((this.onEndGetInvoiceStylesDelegate == null)) {
                this.onEndGetInvoiceStylesDelegate = new EndOperationDelegate(this.OnEndGetInvoiceStyles);
            }
            if ((this.onGetInvoiceStylesCompletedDelegate == null)) {
                this.onGetInvoiceStylesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetInvoiceStylesCompleted);
            }
            base.InvokeAsync(this.onBeginGetInvoiceStylesDelegate, null, this.onEndGetInvoiceStylesDelegate, this.onGetInvoiceStylesCompletedDelegate, userState);
        }

        public void GetPaymentMethodsAsync() {
            this.GetPaymentMethodsAsync(null);
        }

        public void GetPaymentMethodsAsync(object userState) {
            if ((this.onBeginGetPaymentMethodsDelegate == null)) {
                this.onBeginGetPaymentMethodsDelegate = new BeginOperationDelegate(this.OnBeginGetPaymentMethods);
            }
            if ((this.onEndGetPaymentMethodsDelegate == null)) {
                this.onEndGetPaymentMethodsDelegate = new EndOperationDelegate(this.OnEndGetPaymentMethods);
            }
            if ((this.onGetPaymentMethodsCompletedDelegate == null)) {
                this.onGetPaymentMethodsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPaymentMethodsCompleted);
            }
            base.InvokeAsync(this.onBeginGetPaymentMethodsDelegate, null, this.onEndGetPaymentMethodsDelegate, this.onGetPaymentMethodsCompletedDelegate, userState);
        }

        public void GetTaxIndicatorsAsync() {
            this.GetTaxIndicatorsAsync(null);
        }

        public void GetTaxIndicatorsAsync(object userState) {
            if ((this.onBeginGetTaxIndicatorsDelegate == null)) {
                this.onBeginGetTaxIndicatorsDelegate = new BeginOperationDelegate(this.OnBeginGetTaxIndicators);
            }
            if ((this.onEndGetTaxIndicatorsDelegate == null)) {
                this.onEndGetTaxIndicatorsDelegate = new EndOperationDelegate(this.OnEndGetTaxIndicators);
            }
            if ((this.onGetTaxIndicatorsCompletedDelegate == null)) {
                this.onGetTaxIndicatorsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTaxIndicatorsCompleted);
            }
            base.InvokeAsync(this.onBeginGetTaxIndicatorsDelegate, null, this.onEndGetTaxIndicatorsDelegate, this.onGetTaxIndicatorsCompletedDelegate, userState);
        }

        public void GetTreatmentTypesAsync() {
            this.GetTreatmentTypesAsync(null);
        }

        public void GetTreatmentTypesAsync(object userState) {
            if ((this.onBeginGetTreatmentTypesDelegate == null)) {
                this.onBeginGetTreatmentTypesDelegate = new BeginOperationDelegate(this.OnBeginGetTreatmentTypes);
            }
            if ((this.onEndGetTreatmentTypesDelegate == null)) {
                this.onEndGetTreatmentTypesDelegate = new EndOperationDelegate(this.OnEndGetTreatmentTypes);
            }
            if ((this.onGetTreatmentTypesCompletedDelegate == null)) {
                this.onGetTreatmentTypesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTreatmentTypesCompleted);
            }
            base.InvokeAsync(this.onBeginGetTreatmentTypesDelegate, null, this.onEndGetTreatmentTypesDelegate, this.onGetTreatmentTypesCompletedDelegate, userState);
        }

        public void LoginAsync(AgilityCIS.Orion.Services.AgilitySvcProxy.User user) {
            this.LoginAsync(user, null);
        }

        public void LoginAsync(AgilityCIS.Orion.Services.AgilitySvcProxy.User user, object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        user}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }

        public void OpenAsync() {
            this.OpenAsync(null);
        }

        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }

        public void SaveCustomerDetailsAsync(AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerDetails customerDetails) {
            this.SaveCustomerDetailsAsync(customerDetails, null);
        }

        public void SaveCustomerDetailsAsync(AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerDetails customerDetails, object userState) {
            if ((this.onBeginSaveCustomerDetailsDelegate == null)) {
                this.onBeginSaveCustomerDetailsDelegate = new BeginOperationDelegate(this.OnBeginSaveCustomerDetails);
            }
            if ((this.onEndSaveCustomerDetailsDelegate == null)) {
                this.onEndSaveCustomerDetailsDelegate = new EndOperationDelegate(this.OnEndSaveCustomerDetails);
            }
            if ((this.onSaveCustomerDetailsCompletedDelegate == null)) {
                this.onSaveCustomerDetailsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveCustomerDetailsCompleted);
            }
            base.InvokeAsync(this.onBeginSaveCustomerDetailsDelegate, new object[] {
                        customerDetails}, this.onEndSaveCustomerDetailsDelegate, this.onSaveCustomerDetailsCompletedDelegate, userState);
        }

        public void SearchCustomersAsync(AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerSearchCriteria criteria) {
            this.SearchCustomersAsync(criteria, null);
        }

        public void SearchCustomersAsync(AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerSearchCriteria criteria, object userState) {
            if ((this.onBeginSearchCustomersDelegate == null)) {
                this.onBeginSearchCustomersDelegate = new BeginOperationDelegate(this.OnBeginSearchCustomers);
            }
            if ((this.onEndSearchCustomersDelegate == null)) {
                this.onEndSearchCustomersDelegate = new EndOperationDelegate(this.OnEndSearchCustomers);
            }
            if ((this.onSearchCustomersCompletedDelegate == null)) {
                this.onSearchCustomersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchCustomersCompleted);
            }
            base.InvokeAsync(this.onBeginSearchCustomersDelegate, new object[] {
                        criteria}, this.onEndSearchCustomersDelegate, this.onSearchCustomersCompletedDelegate, userState);
        }
		// Protected Methods (1) 

        protected override AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService CreateChannel() {
            return new AgilityServiceClientChannel(this);
        }
		// Private Methods (86) 

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.BeginDeleteCustomer(int seqPartyId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteCustomer(seqPartyId, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.BeginGetBillingCycles(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetBillingCycles(callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.BeginGetCardTypes(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCardTypes(callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.BeginGetCreditCheckScores(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCreditCheckScores(callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.BeginGetCreditControlStatus(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCreditControlStatus(callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.BeginGetCustomerDetails(int customerNo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCustomerDetails(customerNo, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.BeginGetCustomers(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCustomers(callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.BeginGetCustomerSummaryDetails(int seqPartyId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCustomerSummaryDetails(seqPartyId, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.BeginGetInvoiceDeliveries(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetInvoiceDeliveries(callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.BeginGetInvoiceStyles(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetInvoiceStyles(callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.BeginGetPaymentMethods(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPaymentMethods(callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.BeginGetTaxIndicators(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTaxIndicators(callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.BeginGetTreatmentTypes(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTreatmentTypes(callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.BeginLogin(AgilityCIS.Orion.Services.AgilitySvcProxy.User user, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(user, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.BeginSaveCustomerDetails(AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerDetails customerDetails, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveCustomerDetails(customerDetails, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.BeginSearchCustomers(AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerSearchCriteria criteria, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearchCustomers(criteria, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.EndDeleteCustomer(System.IAsyncResult result) {
            return base.Channel.EndDeleteCustomer(result);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.BillingCycle> AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.EndGetBillingCycles(System.IAsyncResult result) {
            return base.Channel.EndGetBillingCycles(result);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CardType> AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.EndGetCardTypes(System.IAsyncResult result) {
            return base.Channel.EndGetCardTypes(result);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CreditCheckScore> AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.EndGetCreditCheckScores(System.IAsyncResult result) {
            return base.Channel.EndGetCreditCheckScores(result);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CreditControlStatus> AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.EndGetCreditControlStatus(System.IAsyncResult result) {
            return base.Channel.EndGetCreditControlStatus(result);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerDetails AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.EndGetCustomerDetails(System.IAsyncResult result) {
            return base.Channel.EndGetCustomerDetails(result);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.Customer> AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.EndGetCustomers(System.IAsyncResult result) {
            return base.Channel.EndGetCustomers(result);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerSummary AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.EndGetCustomerSummaryDetails(System.IAsyncResult result) {
            return base.Channel.EndGetCustomerSummaryDetails(result);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.InvoiceDelivery> AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.EndGetInvoiceDeliveries(System.IAsyncResult result) {
            return base.Channel.EndGetInvoiceDeliveries(result);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.InvoiceStyle> AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.EndGetInvoiceStyles(System.IAsyncResult result) {
            return base.Channel.EndGetInvoiceStyles(result);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.PayMethod> AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.EndGetPaymentMethods(System.IAsyncResult result) {
            return base.Channel.EndGetPaymentMethods(result);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Shell.AgilitySvcProxy.TaxIndicator> AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.EndGetTaxIndicators(System.IAsyncResult result) {
            return base.Channel.EndGetTaxIndicators(result);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.TreatmentType> AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.EndGetTreatmentTypes(System.IAsyncResult result) {
            return base.Channel.EndGetTreatmentTypes(result);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgilityCIS.Orion.Services.AgilitySvcProxy.User AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.EndSaveCustomerDetails(System.IAsyncResult result) {
            return base.Channel.EndSaveCustomerDetails(result);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.Customer> AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService.EndSearchCustomers(System.IAsyncResult result) {
            return base.Channel.EndSearchCustomers(result);
        }

        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }

        private System.IAsyncResult OnBeginDeleteCustomer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int seqPartyId = ((int)(inValues[0]));
            return ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).BeginDeleteCustomer(seqPartyId, callback, asyncState);
        }

        private System.IAsyncResult OnBeginGetBillingCycles(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).BeginGetBillingCycles(callback, asyncState);
        }

        private System.IAsyncResult OnBeginGetCardTypes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).BeginGetCardTypes(callback, asyncState);
        }

        private System.IAsyncResult OnBeginGetCreditCheckScores(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).BeginGetCreditCheckScores(callback, asyncState);
        }

        private System.IAsyncResult OnBeginGetCreditControlStatus(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).BeginGetCreditControlStatus(callback, asyncState);
        }

        private System.IAsyncResult OnBeginGetCustomerDetails(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int customerNo = ((int)(inValues[0]));
            return ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).BeginGetCustomerDetails(customerNo, callback, asyncState);
        }

        private System.IAsyncResult OnBeginGetCustomers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).BeginGetCustomers(callback, asyncState);
        }

        private System.IAsyncResult OnBeginGetCustomerSummaryDetails(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int seqPartyId = ((int)(inValues[0]));
            return ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).BeginGetCustomerSummaryDetails(seqPartyId, callback, asyncState);
        }

        private System.IAsyncResult OnBeginGetInvoiceDeliveries(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).BeginGetInvoiceDeliveries(callback, asyncState);
        }

        private System.IAsyncResult OnBeginGetInvoiceStyles(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).BeginGetInvoiceStyles(callback, asyncState);
        }

        private System.IAsyncResult OnBeginGetPaymentMethods(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).BeginGetPaymentMethods(callback, asyncState);
        }

        private System.IAsyncResult OnBeginGetTaxIndicators(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).BeginGetTaxIndicators(callback, asyncState);
        }

        private System.IAsyncResult OnBeginGetTreatmentTypes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).BeginGetTreatmentTypes(callback, asyncState);
        }

        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AgilityCIS.Orion.Services.AgilitySvcProxy.User user = ((AgilityCIS.Orion.Services.AgilitySvcProxy.User)(inValues[0]));
            return ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).BeginLogin(user, callback, asyncState);
        }

        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }

        private System.IAsyncResult OnBeginSaveCustomerDetails(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerDetails customerDetails = ((AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerDetails)(inValues[0]));
            return ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).BeginSaveCustomerDetails(customerDetails, callback, asyncState);
        }

        private System.IAsyncResult OnBeginSearchCustomers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerSearchCriteria criteria = ((AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerSearchCriteria)(inValues[0]));
            return ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).BeginSearchCustomers(criteria, callback, asyncState);
        }

        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }

        private void OnDeleteCustomerCompleted(object state) {
            if ((this.DeleteCustomerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteCustomerCompleted(this, new DeleteCustomerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }

        private object[] OnEndDeleteCustomer(System.IAsyncResult result) {
            bool retVal = ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).EndDeleteCustomer(result);
            return new object[] {
                    retVal};
        }

        private object[] OnEndGetBillingCycles(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.BillingCycle> retVal = ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).EndGetBillingCycles(result);
            return new object[] {
                    retVal};
        }

        private object[] OnEndGetCardTypes(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CardType> retVal = ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).EndGetCardTypes(result);
            return new object[] {
                    retVal};
        }

        private object[] OnEndGetCreditCheckScores(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CreditCheckScore> retVal = ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).EndGetCreditCheckScores(result);
            return new object[] {
                    retVal};
        }

        private object[] OnEndGetCreditControlStatus(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CreditControlStatus> retVal = ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).EndGetCreditControlStatus(result);
            return new object[] {
                    retVal};
        }

        private object[] OnEndGetCustomerDetails(System.IAsyncResult result) {
            AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerDetails retVal = ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).EndGetCustomerDetails(result);
            return new object[] {
                    retVal};
        }

        private object[] OnEndGetCustomers(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.Customer> retVal = ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).EndGetCustomers(result);
            return new object[] {
                    retVal};
        }

        private object[] OnEndGetCustomerSummaryDetails(System.IAsyncResult result) {
            AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerSummary retVal = ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).EndGetCustomerSummaryDetails(result);
            return new object[] {
                    retVal};
        }

        private object[] OnEndGetInvoiceDeliveries(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.InvoiceDelivery> retVal = ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).EndGetInvoiceDeliveries(result);
            return new object[] {
                    retVal};
        }

        private object[] OnEndGetInvoiceStyles(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.InvoiceStyle> retVal = ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).EndGetInvoiceStyles(result);
            return new object[] {
                    retVal};
        }

        private object[] OnEndGetPaymentMethods(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.PayMethod> retVal = ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).EndGetPaymentMethods(result);
            return new object[] {
                    retVal};
        }

        private object[] OnEndGetTaxIndicators(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Shell.AgilitySvcProxy.TaxIndicator> retVal = ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).EndGetTaxIndicators(result);
            return new object[] {
                    retVal};
        }

        private object[] OnEndGetTreatmentTypes(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.TreatmentType> retVal = ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).EndGetTreatmentTypes(result);
            return new object[] {
                    retVal};
        }

        private object[] OnEndLogin(System.IAsyncResult result) {
            AgilityCIS.Orion.Services.AgilitySvcProxy.User retVal = ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).EndLogin(result);
            return new object[] {
                    retVal};
        }

        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }

        private object[] OnEndSaveCustomerDetails(System.IAsyncResult result) {
            bool retVal = ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).EndSaveCustomerDetails(result);
            return new object[] {
                    retVal};
        }

        private object[] OnEndSearchCustomers(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.Customer> retVal = ((AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService)(this)).EndSearchCustomers(result);
            return new object[] {
                    retVal};
        }

        private void OnGetBillingCyclesCompleted(object state) {
            if ((this.GetBillingCyclesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetBillingCyclesCompleted(this, new GetBillingCyclesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        private void OnGetCardTypesCompleted(object state) {
            if ((this.GetCardTypesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCardTypesCompleted(this, new GetCardTypesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        private void OnGetCreditCheckScoresCompleted(object state) {
            if ((this.GetCreditCheckScoresCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCreditCheckScoresCompleted(this, new GetCreditCheckScoresCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        private void OnGetCreditControlStatusCompleted(object state) {
            if ((this.GetCreditControlStatusCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCreditControlStatusCompleted(this, new GetCreditControlStatusCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        private void OnGetCustomerDetailsCompleted(object state) {
            if ((this.GetCustomerDetailsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCustomerDetailsCompleted(this, new GetCustomerDetailsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        private void OnGetCustomersCompleted(object state) {
            if ((this.GetCustomersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCustomersCompleted(this, new GetCustomersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        private void OnGetCustomerSummaryDetailsCompleted(object state) {
            if ((this.GetCustomerSummaryDetailsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCustomerSummaryDetailsCompleted(this, new GetCustomerSummaryDetailsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        private void OnGetInvoiceDeliveriesCompleted(object state) {
            if ((this.GetInvoiceDeliveriesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetInvoiceDeliveriesCompleted(this, new GetInvoiceDeliveriesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        private void OnGetInvoiceStylesCompleted(object state) {
            if ((this.GetInvoiceStylesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetInvoiceStylesCompleted(this, new GetInvoiceStylesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        private void OnGetPaymentMethodsCompleted(object state) {
            if ((this.GetPaymentMethodsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPaymentMethodsCompleted(this, new GetPaymentMethodsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        private void OnGetTaxIndicatorsCompleted(object state) {
            if ((this.GetTaxIndicatorsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTaxIndicatorsCompleted(this, new GetTaxIndicatorsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        private void OnGetTreatmentTypesCompleted(object state) {
            if ((this.GetTreatmentTypesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTreatmentTypesCompleted(this, new GetTreatmentTypesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }

        private void OnSaveCustomerDetailsCompleted(object state) {
            if ((this.SaveCustomerDetailsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveCustomerDetailsCompleted(this, new SaveCustomerDetailsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        private void OnSearchCustomersCompleted(object state) {
            if ((this.SearchCustomersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchCustomersCompleted(this, new SearchCustomersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

		#endregion Methods 

		#region Nested Classes (1) 


        private class AgilityServiceClientChannel : ChannelBase<AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService>, AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService {
		#region Constructors (1) 

                        public AgilityServiceClientChannel(System.ServiceModel.ClientBase<AgilityCIS.Orion.Shell.AgilitySvcProxy.IAgilityService> client) : 
                    base(client) {
            }

		#endregion Constructors 

		#region Methods (32) 

		// Public Methods (32) 

                        public System.IAsyncResult BeginDeleteCustomer(int seqPartyId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = seqPartyId;
                System.IAsyncResult _result = base.BeginInvoke("DeleteCustomer", _args, callback, asyncState);
                return _result;
            }

                        public System.IAsyncResult BeginGetBillingCycles(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetBillingCycles", _args, callback, asyncState);
                return _result;
            }

                        public System.IAsyncResult BeginGetCardTypes(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetCardTypes", _args, callback, asyncState);
                return _result;
            }

                        public System.IAsyncResult BeginGetCreditCheckScores(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetCreditCheckScores", _args, callback, asyncState);
                return _result;
            }

                        public System.IAsyncResult BeginGetCreditControlStatus(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetCreditControlStatus", _args, callback, asyncState);
                return _result;
            }

                        public System.IAsyncResult BeginGetCustomerDetails(int customerNo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = customerNo;
                System.IAsyncResult _result = base.BeginInvoke("GetCustomerDetails", _args, callback, asyncState);
                return _result;
            }

                        public System.IAsyncResult BeginGetCustomers(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetCustomers", _args, callback, asyncState);
                return _result;
            }

                        public System.IAsyncResult BeginGetCustomerSummaryDetails(int seqPartyId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = seqPartyId;
                System.IAsyncResult _result = base.BeginInvoke("GetCustomerSummaryDetails", _args, callback, asyncState);
                return _result;
            }

                        public System.IAsyncResult BeginGetInvoiceDeliveries(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetInvoiceDeliveries", _args, callback, asyncState);
                return _result;
            }

                        public System.IAsyncResult BeginGetInvoiceStyles(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetInvoiceStyles", _args, callback, asyncState);
                return _result;
            }

                        public System.IAsyncResult BeginGetPaymentMethods(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetPaymentMethods", _args, callback, asyncState);
                return _result;
            }

                        public System.IAsyncResult BeginGetTaxIndicators(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetTaxIndicators", _args, callback, asyncState);
                return _result;
            }

                        public System.IAsyncResult BeginGetTreatmentTypes(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetTreatmentTypes", _args, callback, asyncState);
                return _result;
            }

                        public System.IAsyncResult BeginLogin(AgilityCIS.Orion.Services.AgilitySvcProxy.User user, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = user;
                System.IAsyncResult _result = base.BeginInvoke("Login", _args, callback, asyncState);
                return _result;
            }

                        public System.IAsyncResult BeginSaveCustomerDetails(AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerDetails customerDetails, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = customerDetails;
                System.IAsyncResult _result = base.BeginInvoke("SaveCustomerDetails", _args, callback, asyncState);
                return _result;
            }

                        public System.IAsyncResult BeginSearchCustomers(AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerSearchCriteria criteria, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = criteria;
                System.IAsyncResult _result = base.BeginInvoke("SearchCustomers", _args, callback, asyncState);
                return _result;
            }

                        public bool EndDeleteCustomer(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("DeleteCustomer", _args, result)));
                return _result;
            }

                        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.BillingCycle> EndGetBillingCycles(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.BillingCycle> _result = ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.BillingCycle>)(base.EndInvoke("GetBillingCycles", _args, result)));
                return _result;
            }

                        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CardType> EndGetCardTypes(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CardType> _result = ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CardType>)(base.EndInvoke("GetCardTypes", _args, result)));
                return _result;
            }

                        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CreditCheckScore> EndGetCreditCheckScores(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CreditCheckScore> _result = ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CreditCheckScore>)(base.EndInvoke("GetCreditCheckScores", _args, result)));
                return _result;
            }

                        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CreditControlStatus> EndGetCreditControlStatus(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CreditControlStatus> _result = ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.CreditControlStatus>)(base.EndInvoke("GetCreditControlStatus", _args, result)));
                return _result;
            }

                        public AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerDetails EndGetCustomerDetails(System.IAsyncResult result) {
                object[] _args = new object[0];
                AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerDetails _result = ((AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerDetails)(base.EndInvoke("GetCustomerDetails", _args, result)));
                return _result;
            }

                        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.Customer> EndGetCustomers(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.Customer> _result = ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.Customer>)(base.EndInvoke("GetCustomers", _args, result)));
                return _result;
            }

                        public AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerSummary EndGetCustomerSummaryDetails(System.IAsyncResult result) {
                object[] _args = new object[0];
                AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerSummary _result = ((AgilityCIS.Orion.Services.AgilitySvcProxy.CustomerSummary)(base.EndInvoke("GetCustomerSummaryDetails", _args, result)));
                return _result;
            }

                        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.InvoiceDelivery> EndGetInvoiceDeliveries(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.InvoiceDelivery> _result = ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.InvoiceDelivery>)(base.EndInvoke("GetInvoiceDeliveries", _args, result)));
                return _result;
            }

                        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.InvoiceStyle> EndGetInvoiceStyles(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.InvoiceStyle> _result = ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.InvoiceStyle>)(base.EndInvoke("GetInvoiceStyles", _args, result)));
                return _result;
            }

                        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.PayMethod> EndGetPaymentMethods(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.PayMethod> _result = ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.PayMethod>)(base.EndInvoke("GetPaymentMethods", _args, result)));
                return _result;
            }

                        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Shell.AgilitySvcProxy.TaxIndicator> EndGetTaxIndicators(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Shell.AgilitySvcProxy.TaxIndicator> _result = ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Shell.AgilitySvcProxy.TaxIndicator>)(base.EndInvoke("GetTaxIndicators", _args, result)));
                return _result;
            }

                        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.TreatmentType> EndGetTreatmentTypes(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.TreatmentType> _result = ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.TreatmentType>)(base.EndInvoke("GetTreatmentTypes", _args, result)));
                return _result;
            }

                        public AgilityCIS.Orion.Services.AgilitySvcProxy.User EndLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                AgilityCIS.Orion.Services.AgilitySvcProxy.User _result = ((AgilityCIS.Orion.Services.AgilitySvcProxy.User)(base.EndInvoke("Login", _args, result)));
                return _result;
            }

                        public bool EndSaveCustomerDetails(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("SaveCustomerDetails", _args, result)));
                return _result;
            }

                        public System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.Customer> EndSearchCustomers(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.Customer> _result = ((System.Collections.ObjectModel.ObservableCollection<AgilityCIS.Orion.Services.AgilitySvcProxy.Customer>)(base.EndInvoke("SearchCustomers", _args, result)));
                return _result;
            }

		#endregion Methods 
        }
		#endregion Nested Classes 
    }
}
