//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgilityCIS.Orion.LocalizationManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
		#region Constructors (1) 

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }

		#endregion Constructors 

		#region Properties (135) 

        /// <summary>
        ///   Looks up a localized string similar to Account Details.
        /// </summary>
        public static string ltAccountDetails {
            get {
                return ResourceManager.GetString("ltAccountDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account name.
        /// </summary>
        public static string ltAccountName {
            get {
                return ResourceManager.GetString("ltAccountName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account number.
        /// </summary>
        public static string ltAccountNumber {
            get {
                return ResourceManager.GetString("ltAccountNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string ltActivity {
            get {
                return ResourceManager.GetString("ltActivity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add current customer to campaign.
        /// </summary>
        public static string ltAdd {
            get {
                return ResourceManager.GetString("ltAdd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AGC Rewards.
        /// </summary>
        public static string ltAGCRewards {
            get {
                return ResourceManager.GetString("ltAGCRewards", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string ltAlert {
            get {
                return ResourceManager.GetString("ltAlert", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alert expires.
        /// </summary>
        public static string ltAlertExpires {
            get {
                return ResourceManager.GetString("ltAlertExpires", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Avg. Spend.
        /// </summary>
        public static string ltAvgSpend {
            get {
                return ResourceManager.GetString("ltAvgSpend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string ltBank {
            get {
                return ResourceManager.GetString("ltBank", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bank account name.
        /// </summary>
        public static string ltBankAccountName {
            get {
                return ResourceManager.GetString("ltBankAccountName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bank account no.
        /// </summary>
        public static string ltBankAccountNo {
            get {
                return ResourceManager.GetString("ltBankAccountNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bank details.
        /// </summary>
        public static string ltBankDetails {
            get {
                return ResourceManager.GetString("ltBankDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bill cycle.
        /// </summary>
        public static string ltBillCycle {
            get {
                return ResourceManager.GetString("ltBillCycle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        public static string ltBilling {
            get {
                return ResourceManager.GetString("ltBilling", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Billing limit.
        /// </summary>
        public static string ltBillingLimit {
            get {
                return ResourceManager.GetString("ltBillingLimit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Billing notes.
        /// </summary>
        public static string ltBillingNotes {
            get {
                return ResourceManager.GetString("ltBillingNotes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bond amount held.
        /// </summary>
        public static string ltBondAmountHeld {
            get {
                return ResourceManager.GetString("ltBondAmountHeld", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string ltBranch {
            get {
                return ResourceManager.GetString("ltBranch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add call to customer list.
        /// </summary>
        public static string ltCall {
            get {
                return ResourceManager.GetString("ltCall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Call Note.
        /// </summary>
        public static string ltCallNote {
            get {
                return ResourceManager.GetString("ltCallNote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Calls.
        /// </summary>
        public static string ltCalls {
            get {
                return ResourceManager.GetString("ltCalls", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Campaigns.
        /// </summary>
        public static string ltCampaigns {
            get {
                return ResourceManager.GetString("ltCampaigns", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the changes?.
        /// </summary>
        public static string ltCancelChanges {
            get {
                return ResourceManager.GetString("ltCancelChanges", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card type.
        /// </summary>
        public static string ltCardType {
            get {
                return ResourceManager.GetString("ltCardType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CC Alert.
        /// </summary>
        public static string ltCCAlert {
            get {
                return ResourceManager.GetString("ltCCAlert", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CC Verf. No..
        /// </summary>
        public static string ltCCVerfNo {
            get {
                return ResourceManager.GetString("ltCCVerfNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Charges.
        /// </summary>
        public static string ltCharges {
            get {
                return ResourceManager.GetString("ltCharges", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ltClear {
            get {
                return ResourceManager.GetString("ltClear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        public static string ltClientName {
            get {
                return ResourceManager.GetString("ltClientName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string ltCollapse {
            get {
                return ResourceManager.GetString("ltCollapse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string ltCompanyName {
            get {
                return ResourceManager.GetString("ltCompanyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string ltConfirmation {
            get {
                return ResourceManager.GetString("ltConfirmation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ltContact {
            get {
                return ResourceManager.GetString("ltContact", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string ltContacts {
            get {
                return ResourceManager.GetString("ltContacts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Correspondance.
        /// </summary>
        public static string ltCorrespondance {
            get {
                return ResourceManager.GetString("ltCorrespondance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Correspondence.
        /// </summary>
        public static string ltCorrespondence {
            get {
                return ResourceManager.GetString("ltCorrespondence", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Correspondence by E-mail.
        /// </summary>
        public static string ltCorrespondenceByEmail {
            get {
                return ResourceManager.GetString("ltCorrespondenceByEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Correspondence by Post.
        /// </summary>
        public static string ltCorrespondenceByPost {
            get {
                return ResourceManager.GetString("ltCorrespondenceByPost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credit card details.
        /// </summary>
        public static string ltCreditCardDetails {
            get {
                return ResourceManager.GetString("ltCreditCardDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credit check score.
        /// </summary>
        public static string ltCreditCheckScore {
            get {
                return ResourceManager.GetString("ltCreditCheckScore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credit control status.
        /// </summary>
        public static string ltCreditControlStatus {
            get {
                return ResourceManager.GetString("ltCreditControlStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credit Ctrl.
        /// </summary>
        public static string ltCreditCtrl {
            get {
                return ResourceManager.GetString("ltCreditCtrl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credit limit.
        /// </summary>
        public static string ltCreditLimit {
            get {
                return ResourceManager.GetString("ltCreditLimit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Curent.
        /// </summary>
        public static string ltCurrent {
            get {
                return ResourceManager.GetString("ltCurrent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current accounts only.
        /// </summary>
        public static string ltCurrentaccountsonly {
            get {
                return ResourceManager.GetString("ltCurrentaccountsonly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string ltCustomer {
            get {
                return ResourceManager.GetString("ltCustomer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer name.
        /// </summary>
        public static string ltCustomerName {
            get {
                return ResourceManager.GetString("ltCustomerName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer No.
        /// </summary>
        public static string ltCustomerNo {
            get {
                return ResourceManager.GetString("ltCustomerNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer type.
        /// </summary>
        public static string ltCustomerType {
            get {
                return ResourceManager.GetString("ltCustomerType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date Details Confirmed.
        /// </summary>
        public static string ltDateDetailsConfirmed {
            get {
                return ResourceManager.GetString("ltDateDetailsConfirmed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decisions.
        /// </summary>
        public static string ltDecisions {
            get {
                return ResourceManager.GetString("ltDecisions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete customer.
        /// </summary>
        public static string ltDelete {
            get {
                return ResourceManager.GetString("ltDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string ltDetails {
            get {
                return ResourceManager.GetString("ltDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string ltDeveloper {
            get {
                return ResourceManager.GetString("ltDeveloper", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string ltDocuments {
            get {
                return ResourceManager.GetString("ltDocuments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string ltEmail {
            get {
                return ResourceManager.GetString("ltEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Employer.
        /// </summary>
        public static string ltEmployer {
            get {
                return ResourceManager.GetString("ltEmployer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter Customer No..
        /// </summary>
        public static string ltEnterCustomerNo {
            get {
                return ResourceManager.GetString("ltEnterCustomerNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        public static string ltExpand {
            get {
                return ResourceManager.GetString("ltExpand", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expiry.
        /// </summary>
        public static string ltExpiry {
            get {
                return ResourceManager.GetString("ltExpiry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string ltFax {
            get {
                return ResourceManager.GetString("ltFax", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please complete at least one of the search criteria fields..
        /// </summary>
        public static string ltFillSearchCriteria {
            get {
                return ResourceManager.GetString("ltFillSearchCriteria", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filter Criteria.
        /// </summary>
        public static string ltFilterCriteria {
            get {
                return ResourceManager.GetString("ltFilterCriteria", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        public static string ltFinance {
            get {
                return ResourceManager.GetString("ltFinance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move to first customer list.
        /// </summary>
        public static string ltFirst {
            get {
                return ResourceManager.GetString("ltFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string ltHistory {
            get {
                return ResourceManager.GetString("ltHistory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string ltHome {
            get {
                return ResourceManager.GetString("ltHome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Incl Lease.
        /// </summary>
        public static string ltInclLease {
            get {
                return ResourceManager.GetString("ltInclLease", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have entered and incorrect number or format for Credit Limit.
        /// </summary>
        public static string ltIncorrectCreditLimit {
            get {
                return ResourceManager.GetString("ltIncorrectCreditLimit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        public static string ltIndustry {
            get {
                return ResourceManager.GetString("ltIndustry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invoice cycle.
        /// </summary>
        public static string ltInvoiceCycle {
            get {
                return ResourceManager.GetString("ltInvoiceCycle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invoice delivery.
        /// </summary>
        public static string ltInvoiceDelivery {
            get {
                return ResourceManager.GetString("ltInvoiceDelivery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invoice options.
        /// </summary>
        public static string ltInvoiceOptions {
            get {
                return ResourceManager.GetString("ltInvoiceOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invoice Style.
        /// </summary>
        public static string ltinvoiceStyle {
            get {
                return ResourceManager.GetString("ltinvoiceStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move to last customer list.
        /// </summary>
        public static string ltLast {
            get {
                return ResourceManager.GetString("ltLast", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string ltLastName {
            get {
                return ResourceManager.GetString("ltLastName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run mail merge for customers in the list.
        /// </summary>
        public static string ltMail {
            get {
                return ResourceManager.GetString("ltMail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string ltMaintanance {
            get {
                return ResourceManager.GetString("ltMaintanance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Meter no.
        /// </summary>
        public static string ltMeterNo {
            get {
                return ResourceManager.GetString("ltMeterNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ltName {
            get {
                return ResourceManager.GetString("ltName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move to next customer list.
        /// </summary>
        public static string ltNext {
            get {
                return ResourceManager.GetString("ltNext", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string ltNo {
            get {
                return ResourceManager.GetString("ltNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No clients found that match your search criteria..
        /// </summary>
        public static string ltNoClients {
            get {
                return ResourceManager.GetString("ltNoClients", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No of customers :.
        /// </summary>
        public static string ltnoofcustomers {
            get {
                return ResourceManager.GetString("ltnoofcustomers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No of premises :.
        /// </summary>
        public static string ltNoofpremises {
            get {
                return ResourceManager.GetString("ltNoofpremises", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        public static string ltNoResultsFound {
            get {
                return ResourceManager.GetString("ltNoResultsFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string ltNotes {
            get {
                return ResourceManager.GetString("ltNotes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string ltNumber {
            get {
                return ResourceManager.GetString("ltNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        public static string ltOverdue {
            get {
                return ResourceManager.GetString("ltOverdue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Override.
        /// </summary>
        public static string ltOverride {
            get {
                return ResourceManager.GetString("ltOverride", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ltPassword {
            get {
                return ResourceManager.GetString("ltPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        public static string ltPaymentMethod {
            get {
                return ResourceManager.GetString("ltPaymentMethod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Payment Ref.
        /// </summary>
        public static string ltPaymentRef {
            get {
                return ResourceManager.GetString("ltPaymentRef", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string ltPhone {
            get {
                return ResourceManager.GetString("ltPhone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Phone no.
        /// </summary>
        public static string ltPhoneNo {
            get {
                return ResourceManager.GetString("ltPhoneNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter value in the following fields :.
        /// </summary>
        public static string ltPleaseEnter {
            get {
                return ResourceManager.GetString("ltPleaseEnter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Postal Address.
        /// </summary>
        public static string ltPostalAddress {
            get {
                return ResourceManager.GetString("ltPostalAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string ltPostalCode {
            get {
                return ResourceManager.GetString("ltPostalCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Premise address.
        /// </summary>
        public static string ltPremiseAddress {
            get {
                return ResourceManager.GetString("ltPremiseAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Premise Address sorting not implemented.
        /// </summary>
        public static string ltPremiseAddressSorting {
            get {
                return ResourceManager.GetString("ltPremiseAddressSorting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Premises/IP.
        /// </summary>
        public static string ltPremisesIP {
            get {
                return ResourceManager.GetString("ltPremisesIP", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move to previous customer list.
        /// </summary>
        public static string ltPrevious {
            get {
                return ResourceManager.GetString("ltPrevious", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string ltPriority {
            get {
                return ResourceManager.GetString("ltPriority", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Prompt pay disc.
        /// </summary>
        public static string ltPromptPayDisc {
            get {
                return ResourceManager.GetString("ltPromptPayDisc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string ltProperty {
            get {
                return ResourceManager.GetString("ltProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string ltRecent {
            get {
                return ResourceManager.GetString("ltRecent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refund bond.
        /// </summary>
        public static string ltRefundBond {
            get {
                return ResourceManager.GetString("ltRefundBond", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Relationships.
        /// </summary>
        public static string ltRelationships {
            get {
                return ResourceManager.GetString("ltRelationships", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove customer from campaign.
        /// </summary>
        public static string ltRemove {
            get {
                return ResourceManager.GetString("ltRemove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ltReports {
            get {
                return ResourceManager.GetString("ltReports", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resid. Name.
        /// </summary>
        public static string ltResidenceName {
            get {
                return ResourceManager.GetString("ltResidenceName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Residential Customers.
        /// </summary>
        public static string ltResidentialCustomers {
            get {
                return ResourceManager.GetString("ltResidentialCustomers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sales Code.
        /// </summary>
        public static string ltSalesCode {
            get {
                return ResourceManager.GetString("ltSalesCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string ltSave {
            get {
                return ResourceManager.GetString("ltSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ltSearch {
            get {
                return ResourceManager.GetString("ltSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search Criteria.
        /// </summary>
        public static string ltSearchCriteria {
            get {
                return ResourceManager.GetString("ltSearchCriteria", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search for the customer no.
        /// </summary>
        public static string ltSearchNo {
            get {
                return ResourceManager.GetString("ltSearchNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string ltSearchResults {
            get {
                return ResourceManager.GetString("ltSearchResults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string ltSecurity {
            get {
                return ResourceManager.GetString("ltSecurity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Segments.
        /// </summary>
        public static string ltSegments {
            get {
                return ResourceManager.GetString("ltSegments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string ltServices {
            get {
                return ResourceManager.GetString("ltServices", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Site Address sorting not implemented.
        /// </summary>
        public static string ltSiteSorting {
            get {
                return ResourceManager.GetString("ltSiteSorting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string ltSortby {
            get {
                return ResourceManager.GetString("ltSortby", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Street address.
        /// </summary>
        public static string ltStreetAddress {
            get {
                return ResourceManager.GetString("ltStreetAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Street Name.
        /// </summary>
        public static string ltStreetName {
            get {
                return ResourceManager.GetString("ltStreetName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Supergold card number.
        /// </summary>
        public static string ltSupergoldCardNumber {
            get {
                return ResourceManager.GetString("ltSupergoldCardNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Supply company.
        /// </summary>
        public static string ltSupplyCompany {
            get {
                return ResourceManager.GetString("ltSupplyCompany", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System Event.
        /// </summary>
        public static string ltSystemEvent {
            get {
                return ResourceManager.GetString("ltSystemEvent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tax indicator.
        /// </summary>
        public static string ltTaxIndicator {
            get {
                return ResourceManager.GetString("ltTaxIndicator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total Balance.
        /// </summary>
        public static string ltTotalBalance {
            get {
                return ResourceManager.GetString("ltTotalBalance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Treatment type.
        /// </summary>
        public static string ltTreatmentType {
            get {
                return ResourceManager.GetString("ltTreatmentType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ltType {
            get {
                return ResourceManager.GetString("ltType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ltView {
            get {
                return ResourceManager.GetString("ltView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }

		#endregion Properties 

        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgilityCIS.Orion.LocalizationManager.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
